name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t strapi-app:latest .

      - name: Tag Docker Image
        run: |
          docker tag strapi-app:latest ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest

      - name: Set Image Tag Output
        id: set-tag
        run: |
          echo "image-tag=${{ secrets.DOCKER_USERNAME }}/strapi-app:latest" >> $GITHUB_OUTPUT

    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}