name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.IMAGE_URI }} .

      - name: Tag Docker Image
        run: |
          docker tag strapi-app:latest ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.IMAGE_URI }}

      - name: Save Image URI to file
        run: echo "${{ secrets.IMAGE_URI }}

