name: Deploy to AWS CodeDeploy (Docker)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      # - name: Build and tag Docker image
      #   run: |
      #     docker build -t ${{ secrets.ECR_REPOSITORY }} .

      # - name: Push Docker image to ECR
      #   run: docker push ${{ secrets.ECR_REPOSITORY }}
        
      - name: Upload AppSpec file to S3
        run: |
          aws s3 cp appspec.yaml s3://${{ secrets.S3_BUCKET }}/deploy/appspec.yaml --region ${{ secrets.AWS_REGION }}

      # - name: Register new task definition
      #   id: register_task_definition
      #   run: |
      #     TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
      #       --task-definition strapi-task \
      #       --region ${{ secrets.AWS_REGION }} \
      #       --query "taskDefinition.taskDefinitionArn" \
      #       --output text)

      #     echo "Old Task Definition ARN: $TASK_DEFINITION_ARN"

      #     NEW_TASK_DEFINITION=$(aws ecs register-task-definition \
      #       --family strapi-task \
      #       --region ${{ secrets.AWS_REGION }} \
      #       --task-role-arn "arn:aws:iam::985539759598:role/ecsTaskExecutionRole" \
      #       --execution-role-arn "arn:aws:iam::985539759598:role/ecsTaskExecutionRole" \
      #       --network-mode awsvpc \
      #       --requires-compatibilities "FARGATE" \
      #       --cpu 512 \
      #       --memory 1024 \
      #       --container-definitions "[{\"name\":\"strapi\",\"image\":\"${{ secrets.ECR_REPOSITORY }}:latest\",\"portMappings\":[{\"containerPort\":1337,\"protocol\":\"tcp\"}]}]" \
      #       --output json)

      #     echo "New Task Definition: $NEW_TASK_DEFINITION"

      - name: Create deployment
        run: |
             aws deploy create-deployment \
                --application-name StrapiCodeDeployApp \
                --deployment-group-name StrapiDeploymentGroup \
                --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
                --s3-location bucket=${{ secrets.S3_BUCKET }},key=deploy/appspec.yaml,bundleType=YAML \
                --region ${{ secrets.AWS_REGION }}
      