name: Deploy Strapi App to ECS (Blue/Green)
 
on:
  workflow_dispatch:
  
jobs:
  deploy-blue-green-deployment:
    name: Build and Deploy to ECS Blue Green Deployment
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
 
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }} .
          docker push ${{ secrets.ECR_REPOSITORY }}
 
      - name: Initialize Terraform
        run: |
          cd Terraform2
          terraform init
 
      - name: Apply Terraform to deploy ECS and CodeDeploy
        run: |
          cd Terraform2
          terraform apply -auto-approve -var "image_uri=${{ secrets.ECR_REPOSITORY }}