name: Deploy Strapi with Terraform


on:
    workflow_run:
      workflows:
        - Build and Push to ECR # Name of the ci.yml workflow
      types:
        - completed

jobs:
    deploy-strapi:
        name: Deploy Strapi with Terraform
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.0 # Replace with your required version

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1

            - name: Initialize Terraform
              run: |
                    cd Terraform
                    terraform init \
                    -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
                    -backend-config="key=terraform.tfstate" \
                    -backend-config="region=${{ secrets.TF_BACKEND_REGION }}" \
                    -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_DYNAMO_TABLE }}" \
                    -backend-config="encrypt=true"

            - name: Generate Terraform Plan
              env:
                  IMAGE_URI: ${{ github.event.workflow_run.outputs.image-tag }}
              run: |
                  cd Terraform
                  terraform plan -var "image_uri=${IMAGE_URI}"

            - name: Apply Terraform Configuration
              env:
                IMAGE_URI: ${{ github.event.workflow_run.outputs.image-tag }}
              run: |
                cd Terraform
                terraform apply -var "image_uri=${IMAGE_URI}" --auto-approve

            - name: Destroy Terraform Configuration
              run: |
                    cd Terraform
                    terraform destroy --auto-approve