name: Deploy Strapi with Terraform

on:
    push:
        branches:
            - main

jobs:
    deploy-strapi:
        name: Deploy Strapi with Terraform
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1

            - name: Initialize Terraform
              run: |
                    cd terraform
                    terraform init \
                    -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
                    -backend-config="key=terraform.tfstate" \
                    -backend-config="region=${{ secrets.TF_BACKEND_REGION }}" \
                    -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_DYNAMO_TABLE }}" \
                    -backend-config="encrypt=true"

            - name: Generate Terraform Plan
              run: |
                    cd terraform
                    terraform plan

            - name: Apply Terraform Configuration
              run: |
                    cd terraform
                    terraform apply --auto-approve